Awesome books project - Milestone 2
charlyeneh/Awesome-books-Library pull request #3
Opened 2022-02-09 22:15 UTC by charlyeneh

Hello Reviewer,

In this milestone we did:

- The use of classes was implemented in refactoring the code.
- We also added some styling to the CSS file.
- No linter errors
- Make the design almost the same as the given
- Fixed reviewer issues

Thanks 😁

2022-02-09 22:40 UTC, er-contreras requested changes
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

![almost there](https://media.giphy.com/media/7JsChhLbpj0rJtzimC/giphy.gif)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-09 22:40 UTC, eri8-9 commented on script.js
> +  }
- [ ] The remove button is not working at all. Please kindly fix it

2022-02-09 22:40 UTC, eri8-9 commented on style.css
> +}
- [ ] All the classes 'book_lists' seem to stay in one place and that does not let them be responsive. 
![Screen Shot 2022-02-09 at 16 35 17](https://user-images.githubusercontent.com/67211919/153302491-4d26129d-a5e2-42b1-8313-cf1e0284feb3.png)

2022-02-10 06:16 UTC, Meltrust requested changes
Hi @charlyeneh, 

## Great job fixing the delete button!


Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-10 06:16 UTC, Meltrust commented on script.js
> +  // let colorChange = 0;
- [ ] Kindly please, remove this introduced old piece of commented-out code.  That way, the project will be cleaner 💪

2022-02-10 06:16 UTC, Meltrust commented on script.js
> +    // div.appendChild(hr);
- [ ] Kindly please, remove this introduced old piece of commented-out code.  That way, the project will be cleaner 💪

2022-02-10 06:34 UTC, elyor-doniyorov approved these changes
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
# STATUS APPROVED ✔️ 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-10 06:54 UTC, merged